// Code generated by go-swagger; DO NOT EDIT.

package security_management_j_w_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewResetSecretParams creates a new ResetSecretParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewResetSecretParams() *ResetSecretParams {
	return &ResetSecretParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewResetSecretParamsWithTimeout creates a new ResetSecretParams object
// with the ability to set a timeout on a request.
func NewResetSecretParamsWithTimeout(timeout time.Duration) *ResetSecretParams {
	return &ResetSecretParams{
		timeout: timeout,
	}
}

// NewResetSecretParamsWithContext creates a new ResetSecretParams object
// with the ability to set a context for a request.
func NewResetSecretParamsWithContext(ctx context.Context) *ResetSecretParams {
	return &ResetSecretParams{
		Context: ctx,
	}
}

// NewResetSecretParamsWithHTTPClient creates a new ResetSecretParams object
// with the ability to set a custom HTTPClient for a request.
func NewResetSecretParamsWithHTTPClient(client *http.Client) *ResetSecretParams {
	return &ResetSecretParams{
		HTTPClient: client,
	}
}

/* ResetSecretParams contains all the parameters to send to the API endpoint
   for the reset secret operation.

   Typically these are written to a http.Request.
*/
type ResetSecretParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the reset secret params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ResetSecretParams) WithDefaults() *ResetSecretParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the reset secret params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ResetSecretParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the reset secret params
func (o *ResetSecretParams) WithTimeout(timeout time.Duration) *ResetSecretParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the reset secret params
func (o *ResetSecretParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the reset secret params
func (o *ResetSecretParams) WithContext(ctx context.Context) *ResetSecretParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the reset secret params
func (o *ResetSecretParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the reset secret params
func (o *ResetSecretParams) WithHTTPClient(client *http.Client) *ResetSecretParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the reset secret params
func (o *ResetSecretParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ResetSecretParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
