---
version: "2"
linters:
  default: all
  disable:
    - cyclop
    - err113
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funcorder
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - lll
    - maintidx
    - mnd
    - nestif
    - nlreturn
    - noctx
    - nonamedreturns
    - paralleltest
    - perfsprint
    - revive
    - staticcheck
    - testifylint
    - testpackage
    - usestdlibvars
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    depguard:
      rules:
        main:
          files:
            - "!**/*_a _file.go"
          allow:
            - $gostd
            - github.com/030/logging/pkg/logging
            - github.com/030/mij
            - github.com/030/n3dr/internal/app/n3dr
            - github.com/030/p2iwd/pkg/p2iwd
            - github.com/aws/aws-sdk-go/aws
            - github.com/aws/aws-sdk-go/aws/credentials
            - github.com/aws/aws-sdk-go/aws/session
            - github.com/aws/aws-sdk-go/service/s3/s3manager
            - github.com/go-openapi/runtime/client
            - github.com/go-openapi/strfmt
            - github.com/go-playground/validator/v10
            - github.com/hashicorp/go-retryablehttp
            - github.com/mholt/archives
            - github.com/mitchellh/go-homedir
            - github.com/OpenPeeDeeP
            - github.com/ory/dockertest/v3
            - github.com/ory/dockertest/v3/docker
            - github.com/samber/lo
            - github.com/sirupsen/logrus
            - github.com/spf13/cobra
            - github.com/spf13/viper
            - github.com/stretchr/testify/assert
          deny:
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib errors package
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
