#!/bin/bash -eux

NEXUS_VERSION="${1:-3.16.2}"
NEXUS_API_VERSION="${2:-v1}"
TOOL="${3:-./n3dr}"

validate(){
    if [ -z "$TOOL" ]; then
        echo "No deliverable defined. Assuming that 'go run main.go' 
should be run."
        TOOL="go run main.go"
    fi

    if [ -z "$NEXUS_VERSION" ] || [ -z "$NEXUS_API_VERSION" ]; then
        echo "NEXUS_VERSION and NEXUS_API_VERSION should be specified."
        exit 1
    fi
}

nexus(){
    docker run --rm -d -p 9999:8081 --name nexus sonatype/nexus3:${NEXUS_VERSION}
}

readiness(){
    until docker logs nexus | grep 'Started Sonatype Nexus OSS'
    do
        echo "Nexus unavailable"
        sleep 10
    done
}

# Since nexus 3.17.0 the default 'admin123' was changed by an autogenerated
# one. This function retrieves the autogenerated password and if this file
# is unavailable, the default 'admin123' is returned.
password(){
    if docker exec -it nexus cat /nexus-data/admin.password; then
        export PASSWORD=$(docker exec -it nexus cat /nexus-data/admin.password)
    else
        export PASSWORD="admin123"
    fi
}

upload(){
    echo "Testing upload..."
    $TOOL upload -u admin -p $PASSWORD -r maven-releases -n http://localhost:9999 -v ${NEXUS_API_VERSION}
    echo
}

helper_backup(){
    $TOOL backup -n http://localhost:9999 -u admin -p $PASSWORD -r maven-releases -v ${NEXUS_API_VERSION} $1
}

backup(){
    echo "Testing backup..."
    helper_backup ""
    helper_backup "-z"

    if [ "${NEXUS_VERSION}" == "3.9.0" ]; then
        count_downloads 15
        test_zip 12
    else
        count_downloads 63
        test_zip 24
    fi

    helper_backup "-l" | grep 63

    cleanup_downloads
}

helper_repositories(){
    $TOOL repositories -n http://localhost:9999 -u admin -p $PASSWORD -v ${NEXUS_API_VERSION} $1
}

repositories(){
    echo "Testing repositories..."
    helper_repositories "-a | grep maven-releases"
    helper_repositories "-c | grep 7"
    helper_repositories "-b"
    helper_repositories "-b -z"

    if [ "${NEXUS_VERSION}" == "3.9.0" ]; then
        count_downloads 30
        test_zip 20
    else
        count_downloads 126
        test_zip 48
    fi

    cleanup_downloads
}

cleanup(){
    cleanup_downloads
    docker stop nexus
}

count_downloads(){
    find download -type f | wc -l | grep $1
}

test_zip(){
    du -h n3dr-backup-*zip | grep ${1}K
}

cleanup_downloads(){
    rm -f n3dr-backup-*zip
    rm -rf download
}

main(){
    validate
    nexus
    readiness
    password
    upload
    backup
    repositories
    bats --tap tests.bats
}

trap cleanup EXIT
main