// Code generated by go-swagger; DO NOT EDIT.

package content_selectors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetContentSelectorsParams creates a new GetContentSelectorsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetContentSelectorsParams() *GetContentSelectorsParams {
	return &GetContentSelectorsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetContentSelectorsParamsWithTimeout creates a new GetContentSelectorsParams object
// with the ability to set a timeout on a request.
func NewGetContentSelectorsParamsWithTimeout(timeout time.Duration) *GetContentSelectorsParams {
	return &GetContentSelectorsParams{
		timeout: timeout,
	}
}

// NewGetContentSelectorsParamsWithContext creates a new GetContentSelectorsParams object
// with the ability to set a context for a request.
func NewGetContentSelectorsParamsWithContext(ctx context.Context) *GetContentSelectorsParams {
	return &GetContentSelectorsParams{
		Context: ctx,
	}
}

// NewGetContentSelectorsParamsWithHTTPClient creates a new GetContentSelectorsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetContentSelectorsParamsWithHTTPClient(client *http.Client) *GetContentSelectorsParams {
	return &GetContentSelectorsParams{
		HTTPClient: client,
	}
}

/*
GetContentSelectorsParams contains all the parameters to send to the API endpoint

	for the get content selectors operation.

	Typically these are written to a http.Request.
*/
type GetContentSelectorsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get content selectors params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetContentSelectorsParams) WithDefaults() *GetContentSelectorsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get content selectors params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetContentSelectorsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get content selectors params
func (o *GetContentSelectorsParams) WithTimeout(timeout time.Duration) *GetContentSelectorsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get content selectors params
func (o *GetContentSelectorsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get content selectors params
func (o *GetContentSelectorsParams) WithContext(ctx context.Context) *GetContentSelectorsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get content selectors params
func (o *GetContentSelectorsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get content selectors params
func (o *GetContentSelectorsParams) WithHTTPClient(client *http.Client) *GetContentSelectorsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get content selectors params
func (o *GetContentSelectorsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetContentSelectorsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
