// Code generated by go-swagger; DO NOT EDIT.

package manage_i_q_server_configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateConfigurationReader is a Reader for the UpdateConfiguration structure.
type UpdateConfigurationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateConfigurationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewUpdateConfigurationNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateConfigurationNoContent creates a UpdateConfigurationNoContent with default headers values
func NewUpdateConfigurationNoContent() *UpdateConfigurationNoContent {
	return &UpdateConfigurationNoContent{}
}

/* UpdateConfigurationNoContent describes a response with status code 204, with default header values.

IQ server configuration has been updated
*/
type UpdateConfigurationNoContent struct {
}

func (o *UpdateConfigurationNoContent) Error() string {
	return fmt.Sprintf("[PUT /v1/iq][%d] updateConfigurationNoContent ", 204)
}

func (o *UpdateConfigurationNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
