// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DockerHostedStorageAttributes docker hosted storage attributes
//
// swagger:model DockerHostedStorageAttributes
type DockerHostedStorageAttributes struct {

	// Blob store used to store repository contents
	// Example: default
	BlobStoreName string `json:"blobStoreName,omitempty"`

	// Whether to allow redeploying the 'latest' tag but defer to the Deployment Policy for all other tags
	// Example: true
	LatestPolicy bool `json:"latestPolicy,omitempty"`

	// Whether to validate uploaded content's MIME type appropriate for the repository format
	// Example: true
	// Required: true
	StrictContentTypeValidation *bool `json:"strictContentTypeValidation"`

	// Controls if deployments of and updates to assets are allowed
	// Example: allow_once
	// Required: true
	// Enum: [allow allow_once deny]
	WritePolicy *string `json:"writePolicy"`
}

// Validate validates this docker hosted storage attributes
func (m *DockerHostedStorageAttributes) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStrictContentTypeValidation(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWritePolicy(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DockerHostedStorageAttributes) validateStrictContentTypeValidation(formats strfmt.Registry) error {

	if err := validate.Required("strictContentTypeValidation", "body", m.StrictContentTypeValidation); err != nil {
		return err
	}

	return nil
}

var dockerHostedStorageAttributesTypeWritePolicyPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["allow","allow_once","deny"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		dockerHostedStorageAttributesTypeWritePolicyPropEnum = append(dockerHostedStorageAttributesTypeWritePolicyPropEnum, v)
	}
}

const (

	// DockerHostedStorageAttributesWritePolicyAllow captures enum value "allow"
	DockerHostedStorageAttributesWritePolicyAllow string = "allow"

	// DockerHostedStorageAttributesWritePolicyAllowOnce captures enum value "allow_once"
	DockerHostedStorageAttributesWritePolicyAllowOnce string = "allow_once"

	// DockerHostedStorageAttributesWritePolicyDeny captures enum value "deny"
	DockerHostedStorageAttributesWritePolicyDeny string = "deny"
)

// prop value enum
func (m *DockerHostedStorageAttributes) validateWritePolicyEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, dockerHostedStorageAttributesTypeWritePolicyPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *DockerHostedStorageAttributes) validateWritePolicy(formats strfmt.Registry) error {

	if err := validate.Required("writePolicy", "body", m.WritePolicy); err != nil {
		return err
	}

	// value enum
	if err := m.validateWritePolicyEnum("writePolicy", "body", *m.WritePolicy); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this docker hosted storage attributes based on context it is used
func (m *DockerHostedStorageAttributes) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DockerHostedStorageAttributes) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DockerHostedStorageAttributes) UnmarshalBinary(b []byte) error {
	var res DockerHostedStorageAttributes
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
