// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// S3BlobStoreAPIBucketSecurity s3 blob store Api bucket security
//
// swagger:model S3BlobStoreApiBucketSecurity
type S3BlobStoreAPIBucketSecurity struct {

	// An IAM access key ID for granting access to the S3 bucket
	AccessKeyID string `json:"accessKeyId,omitempty"`

	// An IAM role to assume in order to access the S3 bucket
	Role string `json:"role,omitempty"`

	// The secret access key associated with the specified IAM access key ID
	SecretAccessKey string `json:"secretAccessKey,omitempty"`

	// An AWS STS session token associated with temporary security credentials which grant access to the S3 bucket
	SessionToken string `json:"sessionToken,omitempty"`
}

// Validate validates this s3 blob store Api bucket security
func (m *S3BlobStoreAPIBucketSecurity) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this s3 blob store Api bucket security based on context it is used
func (m *S3BlobStoreAPIBucketSecurity) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *S3BlobStoreAPIBucketSecurity) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *S3BlobStoreAPIBucketSecurity) UnmarshalBinary(b []byte) error {
	var res S3BlobStoreAPIBucketSecurity
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
