// Code generated by go-swagger; DO NOT EDIT.

package support

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new support API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for support API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	Supportzip(params *SupportzipParams, opts ...ClientOption) error

	Supportzippath(params *SupportzippathParams, opts ...ClientOption) (*SupportzippathOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
Supportzip creates and downloads a support zip
*/
func (a *Client) Supportzip(params *SupportzipParams, opts ...ClientOption) error {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewSupportzipParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "supportzip",
		Method:             "POST",
		PathPattern:        "/v1/support/supportzip",
		ProducesMediaTypes: []string{"application/octet-stream"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &SupportzipReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	_, err := a.transport.Submit(op)
	if err != nil {
		return err
	}
	return nil
}

/*
Supportzippath creates a support zip and returns the path
*/
func (a *Client) Supportzippath(params *SupportzippathParams, opts ...ClientOption) (*SupportzippathOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewSupportzippathParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "supportzippath",
		Method:             "POST",
		PathPattern:        "/v1/support/supportzippath",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &SupportzippathReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*SupportzippathOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for supportzippath: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
