package cli

import (
	"fmt"
	"io/ioutil"
	"net/http"

	"github.com/thedevsaddam/gojsonq"
)

// Nexus3All contains the attributes that are used by several functions
type Nexus3All struct {
	URL  string
	User string
	Pass string
}

func repositories() string {
	// Generated by curl-to-Go: https://mholt.github.io/curl-to-go

	req, err := http.NewRequest("GET", "http://localhost:9999/service/rest/v1/repositories", nil)
	if err != nil {
		// handle err
	}
	req.Header.Set("Accept", "application/json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		// handle err
	}
	defer resp.Body.Close()

	var bodyString string
	if resp.StatusCode == http.StatusOK {
		bodyBytes, err := ioutil.ReadAll(resp.Body)
		if err != nil {
			//
		}
		bodyString = string(bodyBytes)
	}
	return bodyString
}

func repositoryNamesJSON(json string) interface{} {
	jq := gojsonq.New().JSONString(json)
	jq.SortBy("name", "asc")
	name := jq.Pluck("name")
	return name
}

func repositoriesSlice() []interface{} {
	return repositoryNamesJSON(repositories()).([]interface{})
}

func RepositoryNames() {
	for _, name := range repositoriesSlice() {
		fmt.Printf("%s\n", name)
	}
}

func CountRepositories() {
	fmt.Println(len(repositoriesSlice()))
}

// Downloads retrieves artifacts from all repositories
func (na Nexus3All) Downloads() error {
	for _, name := range repositoriesSlice() {
		n := Nexus3{URL: na.URL, User: na.User, Pass: na.Pass, Repository: name.(string)}
		err := n.StoreArtifactsOnDisk()
		if err != nil {
			return err
		}
	}
	return nil
}
