// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CreateRepository31Reader is a Reader for the CreateRepository31 structure.
type CreateRepository31Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateRepository31Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateRepository31Created()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewCreateRepository31Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateRepository31Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewCreateRepository31MethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateRepository31Created creates a CreateRepository31Created with default headers values
func NewCreateRepository31Created() *CreateRepository31Created {
	return &CreateRepository31Created{}
}

/*
CreateRepository31Created describes a response with status code 201, with default header values.

Repository created
*/
type CreateRepository31Created struct {
}

// IsSuccess returns true when this create repository31 created response has a 2xx status code
func (o *CreateRepository31Created) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create repository31 created response has a 3xx status code
func (o *CreateRepository31Created) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository31 created response has a 4xx status code
func (o *CreateRepository31Created) IsClientError() bool {
	return false
}

// IsServerError returns true when this create repository31 created response has a 5xx status code
func (o *CreateRepository31Created) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository31 created response a status code equal to that given
func (o *CreateRepository31Created) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the create repository31 created response
func (o *CreateRepository31Created) Code() int {
	return 201
}

func (o *CreateRepository31Created) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/r/group][%d] createRepository31Created ", 201)
}

func (o *CreateRepository31Created) String() string {
	return fmt.Sprintf("[POST /v1/repositories/r/group][%d] createRepository31Created ", 201)
}

func (o *CreateRepository31Created) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateRepository31Unauthorized creates a CreateRepository31Unauthorized with default headers values
func NewCreateRepository31Unauthorized() *CreateRepository31Unauthorized {
	return &CreateRepository31Unauthorized{}
}

/*
CreateRepository31Unauthorized describes a response with status code 401, with default header values.

Authentication required
*/
type CreateRepository31Unauthorized struct {
}

// IsSuccess returns true when this create repository31 unauthorized response has a 2xx status code
func (o *CreateRepository31Unauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository31 unauthorized response has a 3xx status code
func (o *CreateRepository31Unauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository31 unauthorized response has a 4xx status code
func (o *CreateRepository31Unauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository31 unauthorized response has a 5xx status code
func (o *CreateRepository31Unauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository31 unauthorized response a status code equal to that given
func (o *CreateRepository31Unauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the create repository31 unauthorized response
func (o *CreateRepository31Unauthorized) Code() int {
	return 401
}

func (o *CreateRepository31Unauthorized) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/r/group][%d] createRepository31Unauthorized ", 401)
}

func (o *CreateRepository31Unauthorized) String() string {
	return fmt.Sprintf("[POST /v1/repositories/r/group][%d] createRepository31Unauthorized ", 401)
}

func (o *CreateRepository31Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateRepository31Forbidden creates a CreateRepository31Forbidden with default headers values
func NewCreateRepository31Forbidden() *CreateRepository31Forbidden {
	return &CreateRepository31Forbidden{}
}

/*
CreateRepository31Forbidden describes a response with status code 403, with default header values.

Insufficient permissions
*/
type CreateRepository31Forbidden struct {
}

// IsSuccess returns true when this create repository31 forbidden response has a 2xx status code
func (o *CreateRepository31Forbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository31 forbidden response has a 3xx status code
func (o *CreateRepository31Forbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository31 forbidden response has a 4xx status code
func (o *CreateRepository31Forbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository31 forbidden response has a 5xx status code
func (o *CreateRepository31Forbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository31 forbidden response a status code equal to that given
func (o *CreateRepository31Forbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the create repository31 forbidden response
func (o *CreateRepository31Forbidden) Code() int {
	return 403
}

func (o *CreateRepository31Forbidden) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/r/group][%d] createRepository31Forbidden ", 403)
}

func (o *CreateRepository31Forbidden) String() string {
	return fmt.Sprintf("[POST /v1/repositories/r/group][%d] createRepository31Forbidden ", 403)
}

func (o *CreateRepository31Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateRepository31MethodNotAllowed creates a CreateRepository31MethodNotAllowed with default headers values
func NewCreateRepository31MethodNotAllowed() *CreateRepository31MethodNotAllowed {
	return &CreateRepository31MethodNotAllowed{}
}

/*
CreateRepository31MethodNotAllowed describes a response with status code 405, with default header values.

Feature is disabled in High Availability
*/
type CreateRepository31MethodNotAllowed struct {
}

// IsSuccess returns true when this create repository31 method not allowed response has a 2xx status code
func (o *CreateRepository31MethodNotAllowed) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository31 method not allowed response has a 3xx status code
func (o *CreateRepository31MethodNotAllowed) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository31 method not allowed response has a 4xx status code
func (o *CreateRepository31MethodNotAllowed) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository31 method not allowed response has a 5xx status code
func (o *CreateRepository31MethodNotAllowed) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository31 method not allowed response a status code equal to that given
func (o *CreateRepository31MethodNotAllowed) IsCode(code int) bool {
	return code == 405
}

// Code gets the status code for the create repository31 method not allowed response
func (o *CreateRepository31MethodNotAllowed) Code() int {
	return 405
}

func (o *CreateRepository31MethodNotAllowed) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/r/group][%d] createRepository31MethodNotAllowed ", 405)
}

func (o *CreateRepository31MethodNotAllowed) String() string {
	return fmt.Sprintf("[POST /v1/repositories/r/group][%d] createRepository31MethodNotAllowed ", 405)
}

func (o *CreateRepository31MethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
