// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CreateRepository39Reader is a Reader for the CreateRepository39 structure.
type CreateRepository39Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateRepository39Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateRepository39Created()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewCreateRepository39Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateRepository39Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateRepository39Created creates a CreateRepository39Created with default headers values
func NewCreateRepository39Created() *CreateRepository39Created {
	return &CreateRepository39Created{}
}

/*
CreateRepository39Created describes a response with status code 201, with default header values.

Repository created
*/
type CreateRepository39Created struct {
}

// IsSuccess returns true when this create repository39 created response has a 2xx status code
func (o *CreateRepository39Created) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create repository39 created response has a 3xx status code
func (o *CreateRepository39Created) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository39 created response has a 4xx status code
func (o *CreateRepository39Created) IsClientError() bool {
	return false
}

// IsServerError returns true when this create repository39 created response has a 5xx status code
func (o *CreateRepository39Created) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository39 created response a status code equal to that given
func (o *CreateRepository39Created) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the create repository39 created response
func (o *CreateRepository39Created) Code() int {
	return 201
}

func (o *CreateRepository39Created) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/bower/hosted][%d] createRepository39Created ", 201)
}

func (o *CreateRepository39Created) String() string {
	return fmt.Sprintf("[POST /v1/repositories/bower/hosted][%d] createRepository39Created ", 201)
}

func (o *CreateRepository39Created) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateRepository39Unauthorized creates a CreateRepository39Unauthorized with default headers values
func NewCreateRepository39Unauthorized() *CreateRepository39Unauthorized {
	return &CreateRepository39Unauthorized{}
}

/*
CreateRepository39Unauthorized describes a response with status code 401, with default header values.

Authentication required
*/
type CreateRepository39Unauthorized struct {
}

// IsSuccess returns true when this create repository39 unauthorized response has a 2xx status code
func (o *CreateRepository39Unauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository39 unauthorized response has a 3xx status code
func (o *CreateRepository39Unauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository39 unauthorized response has a 4xx status code
func (o *CreateRepository39Unauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository39 unauthorized response has a 5xx status code
func (o *CreateRepository39Unauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository39 unauthorized response a status code equal to that given
func (o *CreateRepository39Unauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the create repository39 unauthorized response
func (o *CreateRepository39Unauthorized) Code() int {
	return 401
}

func (o *CreateRepository39Unauthorized) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/bower/hosted][%d] createRepository39Unauthorized ", 401)
}

func (o *CreateRepository39Unauthorized) String() string {
	return fmt.Sprintf("[POST /v1/repositories/bower/hosted][%d] createRepository39Unauthorized ", 401)
}

func (o *CreateRepository39Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateRepository39Forbidden creates a CreateRepository39Forbidden with default headers values
func NewCreateRepository39Forbidden() *CreateRepository39Forbidden {
	return &CreateRepository39Forbidden{}
}

/*
CreateRepository39Forbidden describes a response with status code 403, with default header values.

Insufficient permissions
*/
type CreateRepository39Forbidden struct {
}

// IsSuccess returns true when this create repository39 forbidden response has a 2xx status code
func (o *CreateRepository39Forbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository39 forbidden response has a 3xx status code
func (o *CreateRepository39Forbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository39 forbidden response has a 4xx status code
func (o *CreateRepository39Forbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository39 forbidden response has a 5xx status code
func (o *CreateRepository39Forbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository39 forbidden response a status code equal to that given
func (o *CreateRepository39Forbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the create repository39 forbidden response
func (o *CreateRepository39Forbidden) Code() int {
	return 403
}

func (o *CreateRepository39Forbidden) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/bower/hosted][%d] createRepository39Forbidden ", 403)
}

func (o *CreateRepository39Forbidden) String() string {
	return fmt.Sprintf("[POST /v1/repositories/bower/hosted][%d] createRepository39Forbidden ", 403)
}

func (o *CreateRepository39Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
