// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CreateRepository35Reader is a Reader for the CreateRepository35 structure.
type CreateRepository35Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateRepository35Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateRepository35Created()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewCreateRepository35Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateRepository35Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewCreateRepository35MethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateRepository35Created creates a CreateRepository35Created with default headers values
func NewCreateRepository35Created() *CreateRepository35Created {
	return &CreateRepository35Created{}
}

/*
CreateRepository35Created describes a response with status code 201, with default header values.

Repository created
*/
type CreateRepository35Created struct {
}

// IsSuccess returns true when this create repository35 created response has a 2xx status code
func (o *CreateRepository35Created) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create repository35 created response has a 3xx status code
func (o *CreateRepository35Created) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository35 created response has a 4xx status code
func (o *CreateRepository35Created) IsClientError() bool {
	return false
}

// IsServerError returns true when this create repository35 created response has a 5xx status code
func (o *CreateRepository35Created) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository35 created response a status code equal to that given
func (o *CreateRepository35Created) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the create repository35 created response
func (o *CreateRepository35Created) Code() int {
	return 201
}

func (o *CreateRepository35Created) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/go/group][%d] createRepository35Created ", 201)
}

func (o *CreateRepository35Created) String() string {
	return fmt.Sprintf("[POST /v1/repositories/go/group][%d] createRepository35Created ", 201)
}

func (o *CreateRepository35Created) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateRepository35Unauthorized creates a CreateRepository35Unauthorized with default headers values
func NewCreateRepository35Unauthorized() *CreateRepository35Unauthorized {
	return &CreateRepository35Unauthorized{}
}

/*
CreateRepository35Unauthorized describes a response with status code 401, with default header values.

Authentication required
*/
type CreateRepository35Unauthorized struct {
}

// IsSuccess returns true when this create repository35 unauthorized response has a 2xx status code
func (o *CreateRepository35Unauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository35 unauthorized response has a 3xx status code
func (o *CreateRepository35Unauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository35 unauthorized response has a 4xx status code
func (o *CreateRepository35Unauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository35 unauthorized response has a 5xx status code
func (o *CreateRepository35Unauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository35 unauthorized response a status code equal to that given
func (o *CreateRepository35Unauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the create repository35 unauthorized response
func (o *CreateRepository35Unauthorized) Code() int {
	return 401
}

func (o *CreateRepository35Unauthorized) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/go/group][%d] createRepository35Unauthorized ", 401)
}

func (o *CreateRepository35Unauthorized) String() string {
	return fmt.Sprintf("[POST /v1/repositories/go/group][%d] createRepository35Unauthorized ", 401)
}

func (o *CreateRepository35Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateRepository35Forbidden creates a CreateRepository35Forbidden with default headers values
func NewCreateRepository35Forbidden() *CreateRepository35Forbidden {
	return &CreateRepository35Forbidden{}
}

/*
CreateRepository35Forbidden describes a response with status code 403, with default header values.

Insufficient permissions
*/
type CreateRepository35Forbidden struct {
}

// IsSuccess returns true when this create repository35 forbidden response has a 2xx status code
func (o *CreateRepository35Forbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository35 forbidden response has a 3xx status code
func (o *CreateRepository35Forbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository35 forbidden response has a 4xx status code
func (o *CreateRepository35Forbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository35 forbidden response has a 5xx status code
func (o *CreateRepository35Forbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository35 forbidden response a status code equal to that given
func (o *CreateRepository35Forbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the create repository35 forbidden response
func (o *CreateRepository35Forbidden) Code() int {
	return 403
}

func (o *CreateRepository35Forbidden) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/go/group][%d] createRepository35Forbidden ", 403)
}

func (o *CreateRepository35Forbidden) String() string {
	return fmt.Sprintf("[POST /v1/repositories/go/group][%d] createRepository35Forbidden ", 403)
}

func (o *CreateRepository35Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateRepository35MethodNotAllowed creates a CreateRepository35MethodNotAllowed with default headers values
func NewCreateRepository35MethodNotAllowed() *CreateRepository35MethodNotAllowed {
	return &CreateRepository35MethodNotAllowed{}
}

/*
CreateRepository35MethodNotAllowed describes a response with status code 405, with default header values.

Feature is disabled in High Availability
*/
type CreateRepository35MethodNotAllowed struct {
}

// IsSuccess returns true when this create repository35 method not allowed response has a 2xx status code
func (o *CreateRepository35MethodNotAllowed) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create repository35 method not allowed response has a 3xx status code
func (o *CreateRepository35MethodNotAllowed) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create repository35 method not allowed response has a 4xx status code
func (o *CreateRepository35MethodNotAllowed) IsClientError() bool {
	return true
}

// IsServerError returns true when this create repository35 method not allowed response has a 5xx status code
func (o *CreateRepository35MethodNotAllowed) IsServerError() bool {
	return false
}

// IsCode returns true when this create repository35 method not allowed response a status code equal to that given
func (o *CreateRepository35MethodNotAllowed) IsCode(code int) bool {
	return code == 405
}

// Code gets the status code for the create repository35 method not allowed response
func (o *CreateRepository35MethodNotAllowed) Code() int {
	return 405
}

func (o *CreateRepository35MethodNotAllowed) Error() string {
	return fmt.Sprintf("[POST /v1/repositories/go/group][%d] createRepository35MethodNotAllowed ", 405)
}

func (o *CreateRepository35MethodNotAllowed) String() string {
	return fmt.Sprintf("[POST /v1/repositories/go/group][%d] createRepository35MethodNotAllowed ", 405)
}

func (o *CreateRepository35MethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
