// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateRepository34Reader is a Reader for the UpdateRepository34 structure.
type UpdateRepository34Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateRepository34Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewUpdateRepository34NoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewUpdateRepository34Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewUpdateRepository34Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateRepository34NoContent creates a UpdateRepository34NoContent with default headers values
func NewUpdateRepository34NoContent() *UpdateRepository34NoContent {
	return &UpdateRepository34NoContent{}
}

/* UpdateRepository34NoContent describes a response with status code 204, with default header values.

Repository updated
*/
type UpdateRepository34NoContent struct {
}

func (o *UpdateRepository34NoContent) Error() string {
	return fmt.Sprintf("[PUT /v1/repositories/cocoapods/proxy/{repositoryName}][%d] updateRepository34NoContent ", 204)
}

func (o *UpdateRepository34NoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateRepository34Unauthorized creates a UpdateRepository34Unauthorized with default headers values
func NewUpdateRepository34Unauthorized() *UpdateRepository34Unauthorized {
	return &UpdateRepository34Unauthorized{}
}

/* UpdateRepository34Unauthorized describes a response with status code 401, with default header values.

Authentication required
*/
type UpdateRepository34Unauthorized struct {
}

func (o *UpdateRepository34Unauthorized) Error() string {
	return fmt.Sprintf("[PUT /v1/repositories/cocoapods/proxy/{repositoryName}][%d] updateRepository34Unauthorized ", 401)
}

func (o *UpdateRepository34Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateRepository34Forbidden creates a UpdateRepository34Forbidden with default headers values
func NewUpdateRepository34Forbidden() *UpdateRepository34Forbidden {
	return &UpdateRepository34Forbidden{}
}

/* UpdateRepository34Forbidden describes a response with status code 403, with default header values.

Insufficient permissions
*/
type UpdateRepository34Forbidden struct {
}

func (o *UpdateRepository34Forbidden) Error() string {
	return fmt.Sprintf("[PUT /v1/repositories/cocoapods/proxy/{repositoryName}][%d] updateRepository34Forbidden ", 403)
}

func (o *UpdateRepository34Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
