// Code generated by go-swagger; DO NOT EDIT.

package security_management_privileges

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CreatePrivilegeReader is a Reader for the CreatePrivilege structure.
type CreatePrivilegeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreatePrivilegeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 400:
		result := NewCreatePrivilegeBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreatePrivilegeForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreatePrivilegeBadRequest creates a CreatePrivilegeBadRequest with default headers values
func NewCreatePrivilegeBadRequest() *CreatePrivilegeBadRequest {
	return &CreatePrivilegeBadRequest{}
}

/* CreatePrivilegeBadRequest describes a response with status code 400, with default header values.

Privilege object not configured properly.
*/
type CreatePrivilegeBadRequest struct {
}

func (o *CreatePrivilegeBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/security/privileges/wildcard][%d] createPrivilegeBadRequest ", 400)
}

func (o *CreatePrivilegeBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreatePrivilegeForbidden creates a CreatePrivilegeForbidden with default headers values
func NewCreatePrivilegeForbidden() *CreatePrivilegeForbidden {
	return &CreatePrivilegeForbidden{}
}

/* CreatePrivilegeForbidden describes a response with status code 403, with default header values.

The user does not have permission to perform the operation.
*/
type CreatePrivilegeForbidden struct {
}

func (o *CreatePrivilegeForbidden) Error() string {
	return fmt.Sprintf("[POST /v1/security/privileges/wildcard][%d] createPrivilegeForbidden ", 403)
}

func (o *CreatePrivilegeForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
