// Code generated by goswagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateRepository38Reader is a Reader for the UpdateRepository38 structure.
type UpdateRepository38Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateRepository38Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewUpdateRepository38NoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewUpdateRepository38Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewUpdateRepository38Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateRepository38NoContent creates a UpdateRepository38NoContent with default headers values
func NewUpdateRepository38NoContent() *UpdateRepository38NoContent {
	return &UpdateRepository38NoContent{}
}

/* UpdateRepository38NoContent describes a response with status code 204, with default header values.

Repository updated
*/
type UpdateRepository38NoContent struct {
}

func (o *UpdateRepository38NoContent) Error() string {
	return fmt.Sprintf("[PUT /v1/repositories/bower/group/{repositoryName}][%d] updateRepository38NoContent ", 204)
}

func (o *UpdateRepository38NoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateRepository38Unauthorized creates a UpdateRepository38Unauthorized with default headers values
func NewUpdateRepository38Unauthorized() *UpdateRepository38Unauthorized {
	return &UpdateRepository38Unauthorized{}
}

/* UpdateRepository38Unauthorized describes a response with status code 401, with default header values.

Authentication required
*/
type UpdateRepository38Unauthorized struct {
}

func (o *UpdateRepository38Unauthorized) Error() string {
	return fmt.Sprintf("[PUT /v1/repositories/bower/group/{repositoryName}][%d] updateRepository38Unauthorized ", 401)
}

func (o *UpdateRepository38Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateRepository38Forbidden creates a UpdateRepository38Forbidden with default headers values
func NewUpdateRepository38Forbidden() *UpdateRepository38Forbidden {
	return &UpdateRepository38Forbidden{}
}

/* UpdateRepository38Forbidden describes a response with status code 403, with default header values.

Insufficient permissions
*/
type UpdateRepository38Forbidden struct {
}

func (o *UpdateRepository38Forbidden) Error() string {
	return fmt.Sprintf("[PUT /v1/repositories/bower/group/{repositoryName}][%d] updateRepository38Forbidden ", 403)
}

func (o *UpdateRepository38Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
