// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateRepository16Reader is a Reader for the UpdateRepository16 structure.
type UpdateRepository16Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateRepository16Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewUpdateRepository16NoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewUpdateRepository16Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewUpdateRepository16Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateRepository16NoContent creates a UpdateRepository16NoContent with default headers values
func NewUpdateRepository16NoContent() *UpdateRepository16NoContent {
	return &UpdateRepository16NoContent{}
}

/* UpdateRepository16NoContent describes a response with status code 204, with default header values.

Repository updated
*/
type UpdateRepository16NoContent struct {
}

func (o *UpdateRepository16NoContent) Error() string {
	return fmt.Sprintf("[PUT /v1/repositories/rubygems/proxy/{repositoryName}][%d] updateRepository16NoContent ", 204)
}

func (o *UpdateRepository16NoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateRepository16Unauthorized creates a UpdateRepository16Unauthorized with default headers values
func NewUpdateRepository16Unauthorized() *UpdateRepository16Unauthorized {
	return &UpdateRepository16Unauthorized{}
}

/* UpdateRepository16Unauthorized describes a response with status code 401, with default header values.

Authentication required
*/
type UpdateRepository16Unauthorized struct {
}

func (o *UpdateRepository16Unauthorized) Error() string {
	return fmt.Sprintf("[PUT /v1/repositories/rubygems/proxy/{repositoryName}][%d] updateRepository16Unauthorized ", 401)
}

func (o *UpdateRepository16Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateRepository16Forbidden creates a UpdateRepository16Forbidden with default headers values
func NewUpdateRepository16Forbidden() *UpdateRepository16Forbidden {
	return &UpdateRepository16Forbidden{}
}

/* UpdateRepository16Forbidden describes a response with status code 403, with default header values.

Insufficient permissions
*/
type UpdateRepository16Forbidden struct {
}

func (o *UpdateRepository16Forbidden) Error() string {
	return fmt.Sprintf("[PUT /v1/repositories/rubygems/proxy/{repositoryName}][%d] updateRepository16Forbidden ", 403)
}

func (o *UpdateRepository16Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
