// Code generated by go-swagger; DO NOT EDIT.

package repository_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateRepository37Reader is a Reader for the UpdateRepository37 structure.
type UpdateRepository37Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateRepository37Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewUpdateRepository37NoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewUpdateRepository37Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewUpdateRepository37Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateRepository37NoContent creates a UpdateRepository37NoContent with default headers values
func NewUpdateRepository37NoContent() *UpdateRepository37NoContent {
	return &UpdateRepository37NoContent{}
}

/* UpdateRepository37NoContent describes a response with status code 204, with default header values.

Repository updated
*/
type UpdateRepository37NoContent struct {
}

func (o *UpdateRepository37NoContent) Error() string {
	return fmt.Sprintf("[PUT /v1/repositories/p2/proxy/{repositoryName}][%d] updateRepository37NoContent ", 204)
}

func (o *UpdateRepository37NoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateRepository37Unauthorized creates a UpdateRepository37Unauthorized with default headers values
func NewUpdateRepository37Unauthorized() *UpdateRepository37Unauthorized {
	return &UpdateRepository37Unauthorized{}
}

/* UpdateRepository37Unauthorized describes a response with status code 401, with default header values.

Authentication required
*/
type UpdateRepository37Unauthorized struct {
}

func (o *UpdateRepository37Unauthorized) Error() string {
	return fmt.Sprintf("[PUT /v1/repositories/p2/proxy/{repositoryName}][%d] updateRepository37Unauthorized ", 401)
}

func (o *UpdateRepository37Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateRepository37Forbidden creates a UpdateRepository37Forbidden with default headers values
func NewUpdateRepository37Forbidden() *UpdateRepository37Forbidden {
	return &UpdateRepository37Forbidden{}
}

/* UpdateRepository37Forbidden describes a response with status code 403, with default header values.

Insufficient permissions
*/
type UpdateRepository37Forbidden struct {
}

func (o *UpdateRepository37Forbidden) Error() string {
	return fmt.Sprintf("[PUT /v1/repositories/p2/proxy/{repositoryName}][%d] updateRepository37Forbidden ", 403)
}

func (o *UpdateRepository37Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
