// Code generated by go-swagger; DO NOT EDIT.

package blob_store

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CreateFileBlobStoreReader is a Reader for the CreateFileBlobStore structure.
type CreateFileBlobStoreReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateFileBlobStoreReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewCreateFileBlobStoreNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewCreateFileBlobStoreForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateFileBlobStoreNoContent creates a CreateFileBlobStoreNoContent with default headers values
func NewCreateFileBlobStoreNoContent() *CreateFileBlobStoreNoContent {
	return &CreateFileBlobStoreNoContent{}
}

/*
CreateFileBlobStoreNoContent describes a response with status code 204, with default header values.

Success
*/
type CreateFileBlobStoreNoContent struct {
}

// IsSuccess returns true when this create file blob store no content response has a 2xx status code
func (o *CreateFileBlobStoreNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create file blob store no content response has a 3xx status code
func (o *CreateFileBlobStoreNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create file blob store no content response has a 4xx status code
func (o *CreateFileBlobStoreNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this create file blob store no content response has a 5xx status code
func (o *CreateFileBlobStoreNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this create file blob store no content response a status code equal to that given
func (o *CreateFileBlobStoreNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the create file blob store no content response
func (o *CreateFileBlobStoreNoContent) Code() int {
	return 204
}

func (o *CreateFileBlobStoreNoContent) Error() string {
	return fmt.Sprintf("[POST /v1/blobstores/file][%d] createFileBlobStoreNoContent ", 204)
}

func (o *CreateFileBlobStoreNoContent) String() string {
	return fmt.Sprintf("[POST /v1/blobstores/file][%d] createFileBlobStoreNoContent ", 204)
}

func (o *CreateFileBlobStoreNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateFileBlobStoreForbidden creates a CreateFileBlobStoreForbidden with default headers values
func NewCreateFileBlobStoreForbidden() *CreateFileBlobStoreForbidden {
	return &CreateFileBlobStoreForbidden{}
}

/*
CreateFileBlobStoreForbidden describes a response with status code 403, with default header values.

Insufficient permissions
*/
type CreateFileBlobStoreForbidden struct {
}

// IsSuccess returns true when this create file blob store forbidden response has a 2xx status code
func (o *CreateFileBlobStoreForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create file blob store forbidden response has a 3xx status code
func (o *CreateFileBlobStoreForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create file blob store forbidden response has a 4xx status code
func (o *CreateFileBlobStoreForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create file blob store forbidden response has a 5xx status code
func (o *CreateFileBlobStoreForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create file blob store forbidden response a status code equal to that given
func (o *CreateFileBlobStoreForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the create file blob store forbidden response
func (o *CreateFileBlobStoreForbidden) Code() int {
	return 403
}

func (o *CreateFileBlobStoreForbidden) Error() string {
	return fmt.Sprintf("[POST /v1/blobstores/file][%d] createFileBlobStoreForbidden ", 403)
}

func (o *CreateFileBlobStoreForbidden) String() string {
	return fmt.Sprintf("[POST /v1/blobstores/file][%d] createFileBlobStoreForbidden ", 403)
}

func (o *CreateFileBlobStoreForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
