// Code generated by go-swagger; DO NOT EDIT.

package blob_store

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewQuotaStatusParams creates a new QuotaStatusParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewQuotaStatusParams() *QuotaStatusParams {
	return &QuotaStatusParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewQuotaStatusParamsWithTimeout creates a new QuotaStatusParams object
// with the ability to set a timeout on a request.
func NewQuotaStatusParamsWithTimeout(timeout time.Duration) *QuotaStatusParams {
	return &QuotaStatusParams{
		timeout: timeout,
	}
}

// NewQuotaStatusParamsWithContext creates a new QuotaStatusParams object
// with the ability to set a context for a request.
func NewQuotaStatusParamsWithContext(ctx context.Context) *QuotaStatusParams {
	return &QuotaStatusParams{
		Context: ctx,
	}
}

// NewQuotaStatusParamsWithHTTPClient creates a new QuotaStatusParams object
// with the ability to set a custom HTTPClient for a request.
func NewQuotaStatusParamsWithHTTPClient(client *http.Client) *QuotaStatusParams {
	return &QuotaStatusParams{
		HTTPClient: client,
	}
}

/*
QuotaStatusParams contains all the parameters to send to the API endpoint

	for the quota status operation.

	Typically these are written to a http.Request.
*/
type QuotaStatusParams struct {

	// Name.
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the quota status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QuotaStatusParams) WithDefaults() *QuotaStatusParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the quota status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QuotaStatusParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the quota status params
func (o *QuotaStatusParams) WithTimeout(timeout time.Duration) *QuotaStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the quota status params
func (o *QuotaStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the quota status params
func (o *QuotaStatusParams) WithContext(ctx context.Context) *QuotaStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the quota status params
func (o *QuotaStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the quota status params
func (o *QuotaStatusParams) WithHTTPClient(client *http.Client) *QuotaStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the quota status params
func (o *QuotaStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the quota status params
func (o *QuotaStatusParams) WithName(name string) *QuotaStatusParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the quota status params
func (o *QuotaStatusParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *QuotaStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
