// Code generated by go-swagger; DO NOT EDIT.

package lifecycle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewBounceParams creates a new BounceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewBounceParams() *BounceParams {
	return &BounceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewBounceParamsWithTimeout creates a new BounceParams object
// with the ability to set a timeout on a request.
func NewBounceParamsWithTimeout(timeout time.Duration) *BounceParams {
	return &BounceParams{
		timeout: timeout,
	}
}

// NewBounceParamsWithContext creates a new BounceParams object
// with the ability to set a context for a request.
func NewBounceParamsWithContext(ctx context.Context) *BounceParams {
	return &BounceParams{
		Context: ctx,
	}
}

// NewBounceParamsWithHTTPClient creates a new BounceParams object
// with the ability to set a custom HTTPClient for a request.
func NewBounceParamsWithHTTPClient(client *http.Client) *BounceParams {
	return &BounceParams{
		HTTPClient: client,
	}
}

/*
BounceParams contains all the parameters to send to the API endpoint

	for the bounce operation.

	Typically these are written to a http.Request.
*/
type BounceParams struct {

	/* Body.

	   The phase to bounce
	*/
	Body string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the bounce params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *BounceParams) WithDefaults() *BounceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the bounce params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *BounceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the bounce params
func (o *BounceParams) WithTimeout(timeout time.Duration) *BounceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the bounce params
func (o *BounceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the bounce params
func (o *BounceParams) WithContext(ctx context.Context) *BounceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the bounce params
func (o *BounceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the bounce params
func (o *BounceParams) WithHTTPClient(client *http.Client) *BounceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the bounce params
func (o *BounceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the bounce params
func (o *BounceParams) WithBody(body string) *BounceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the bounce params
func (o *BounceParams) SetBody(body string) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *BounceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
