// Code generated by go-swagger; DO NOT EDIT.

package product_licensing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/030/n3dr/internal/goswagger/models"
)

// SetLicenseReader is a Reader for the SetLicense structure.
type SetLicenseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetLicenseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSetLicenseOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSetLicenseOK creates a SetLicenseOK with default headers values
func NewSetLicenseOK() *SetLicenseOK {
	return &SetLicenseOK{}
}

/* SetLicenseOK describes a response with status code 200, with default header values.

successful operation
*/
type SetLicenseOK struct {
	Payload *models.APILicenseDetailsXO
}

func (o *SetLicenseOK) Error() string {
	return fmt.Sprintf("[POST /v1/system/license][%d] setLicenseOK  %+v", 200, o.Payload)
}
func (o *SetLicenseOK) GetPayload() *models.APILicenseDetailsXO {
	return o.Payload
}

func (o *SetLicenseOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APILicenseDetailsXO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
