// Code generated by go-swagger; DO NOT EDIT.

package routing_rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteRoutingRuleParams creates a new DeleteRoutingRuleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteRoutingRuleParams() *DeleteRoutingRuleParams {
	return &DeleteRoutingRuleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteRoutingRuleParamsWithTimeout creates a new DeleteRoutingRuleParams object
// with the ability to set a timeout on a request.
func NewDeleteRoutingRuleParamsWithTimeout(timeout time.Duration) *DeleteRoutingRuleParams {
	return &DeleteRoutingRuleParams{
		timeout: timeout,
	}
}

// NewDeleteRoutingRuleParamsWithContext creates a new DeleteRoutingRuleParams object
// with the ability to set a context for a request.
func NewDeleteRoutingRuleParamsWithContext(ctx context.Context) *DeleteRoutingRuleParams {
	return &DeleteRoutingRuleParams{
		Context: ctx,
	}
}

// NewDeleteRoutingRuleParamsWithHTTPClient creates a new DeleteRoutingRuleParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteRoutingRuleParamsWithHTTPClient(client *http.Client) *DeleteRoutingRuleParams {
	return &DeleteRoutingRuleParams{
		HTTPClient: client,
	}
}

/*
DeleteRoutingRuleParams contains all the parameters to send to the API endpoint

	for the delete routing rule operation.

	Typically these are written to a http.Request.
*/
type DeleteRoutingRuleParams struct {

	/* Name.

	   The name of the routing rule to delete
	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete routing rule params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteRoutingRuleParams) WithDefaults() *DeleteRoutingRuleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete routing rule params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteRoutingRuleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete routing rule params
func (o *DeleteRoutingRuleParams) WithTimeout(timeout time.Duration) *DeleteRoutingRuleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete routing rule params
func (o *DeleteRoutingRuleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete routing rule params
func (o *DeleteRoutingRuleParams) WithContext(ctx context.Context) *DeleteRoutingRuleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete routing rule params
func (o *DeleteRoutingRuleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete routing rule params
func (o *DeleteRoutingRuleParams) WithHTTPClient(client *http.Client) *DeleteRoutingRuleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete routing rule params
func (o *DeleteRoutingRuleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the delete routing rule params
func (o *DeleteRoutingRuleParams) WithName(name string) *DeleteRoutingRuleParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the delete routing rule params
func (o *DeleteRoutingRuleParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteRoutingRuleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
