---
name: MCVS-PR-validation-action
"on":
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize
  workflow_call:
permissions:
  contents: read
  pull-requests: read
jobs:
  MCVS-PR-validation-action:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: schubergphilis/mcvs-pr-validation-action@v0.2.1
